# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
# Importing the NumPy package
import numpy as np 

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [3]:
# creating 1-dimensional numpy array
one_dim = np.array(['a', 'b', 'c', 'd'])
print(one_dim)

# creating 2-dimensional numpy array
two_dim = np.array([[1, 3, 5],[34, 42, 19]])
print(two_dim)

# creating 3-dimensional numpy array
three_dim = np.array([[[1, 3, 5, 7], [2, 4, 6, 8]], [[2, 4, 3, 9], [10, 9, 8,7]]])
print(three_dim)

['a' 'b' 'c' 'd']
[[ 1  3  5]
 [34 42 19]]
[[[ 1  3  5  7]
  [ 2  4  6  8]]

 [[ 2  4  3  9]
  [10  9  8  7]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [4]:
# Creating 2d numpy array
my_2d_array = np.array([['age', 'height', 'weight'],[30, 156, 210]])

# Printing the number of array dimensions
print(f"This is a {my_2d_array.ndim} dimensional array")

# Printing tuple of array dimensions
print(f"The array has a dimension of {my_2d_array.shape} in the x and y axis")

# Printing number of elements in array
print(f"There are {my_2d_array.size} elements in the array")

# Printing data type of array elements 
print(f"The data type for this array is {my_2d_array.dtype}")

# Printing length of array is bytes
print(f"The array is {my_2d_array.itemsize} bytes")

# Printing Python buffer object pointing to the start of the array’s data
print(f"Buffer: {my_2d_array.data}")

# Printing Total bytes consumed by the elements of the array
print(f"{my_2d_array.nbytes} bytes was consumed by the elements of the array")

This is a 2 dimensional array
The array has a dimension of (2, 3) in the x and y axis
There are 6 elements in the array
The data type for this array is <U6
The array is 24 bytes
Buffer: <memory at 0x7fc2ab0886c0>
144 bytes was consumed by the elements of the array


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [5]:
# Creating a 2-dimensional array with 5 rows and 5 columns filled with ones 
array_ones = np.ones((5, 5))
print(f"Below is a 5 x 5 array filled with ones: \n {array_ones}")

# Creating a 4 x 4 zero matrix
array_zeros = np.zeros((4,4))
print(f" Below is a 4 x 4 zero matrix \n {array_zeros}")

# Creating a 2 x 4 array without initializing entries
array_empty = np.empty((2, 4))
print(array_empty)

# Creating a 30 x 80 dash grid 
array_grid = np.full((30, 80), '-')
print(f"Below is the grid for Conway's Game of Life: \n {array_grid}")

# Creating an array of even numbers between 0 and 20
array_even_0to20 = np.linspace(0, 20 ,10, dtype = 'int', endpoint = False)
print(f"The even numbers between 0 and 20 are: {array_even_0to20}")

# Generating random 5 x 5 arrays
array_random = np.random.random((5,5))
print(array_random)


Below is a 5 x 5 array filled with ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 Below is a 4 x 4 zero matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.49166815e-154 1.49166815e-154 2.47032823e-323 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.49166815e-154 2.68678921e+154]]
Below is the grid for Conway's Game of Life: 
 [['-' '-' '-' ... '-' '-' '-']
 ['-' '-' '-' ... '-' '-' '-']
 ['-' '-' '-' ... '-' '-' '-']
 ...
 ['-' '-' '-' ... '-' '-' '-']
 ['-' '-' '-' ... '-' '-' '-']
 ['-' '-' '-' ... '-' '-' '-']]
The even numbers between 0 and 20 are: [ 0  2  4  6  8 10 12 14 16 18]
[[0.99962514 0.14200529 0.17281393 0.5385365  0.2416037 ]
 [0.47918928 0.56524346 0.73943562 0.36326936 0.17257712]
 [0.30809637 0.05660007 0.95030514 0.21522251 0.60560959]
 [0.77049309 0.31809108 0.78462494 0.61876266 0.33013315]
 [0.41592419 0.69157636 0.04558018 0.12670534 0.09799972]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [22]:
# Creating arrays 
array_1 = np.ones((5,2))
array_2 = np.random.random((4,1,2))

# Addition of arrays
array_addition = print(f"'array_1' + 'array_2' = {array_1 + array_2}")

# Multiplication of arrays
array_multiplication = print(f"'array_1' * 'array_2': {array_1 + array_2}")

# Subtraction of arrays 
array_subtruction = print(f"'array_1' - 'array_2' = {array_1 - array_2}")

# Creating arrays of defying the broadcasting rules
array_3 = np.ones((5,2,4))
array_4 = np.random.random((2,3,2))

# Multiplication of arrays
array_add = print(f"'array_3' + 'array_3': {array_3 + array_4}")



'array_1' + 'array_2' = [[[1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]]

 [[1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]]

 [[1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]]

 [[1.02646787 1.22559951]
  [1.02646787 1.22559951]
  [1.02646787 1.22559951]
  [1.02646787 1.22559951]
  [1.02646787 1.22559951]]]
'array_1' * 'array_2': [[[1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]
  [1.90318751 1.05651834]]

 [[1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]
  [1.29035101 1.13597266]]

 [[1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]
  [1.74516174 1.93977   ]]

 [[1.02646787 1.22559951]
  [

ValueError: operands could not be broadcast together with shapes (5,2,4) (2,3,2) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [49]:
# Creating 2-d array
array_5 = np.array([[1, 2, 5, 9],[2, 3, 7, 10]])
array_6 = np.array([[2, 5, 1, 7], [4, 8, 6, 0]])

# Sum of array elements
print(f"The sum of elements in array_5 is: \n {np.sum(array_5)}")

# Minimum element in array_5 and array_6
print(f"The minimum of elements between array_5 and array_6 is: \n {np.minimum(array_5, array_6)}")

# Maximum element in array_5 and array_6
print(f"The maximum of elements between array_5 and array_6 is: \n {np.maximum(array_5, array_6)}")

# Cummulative sum of elements in array_5
print(f"The cummulative sum of elements in array_5 is: \n {np.cumsum(array_5)}")

# Mean of elements in array_5
print(f"The mean of elements in array_5 is {np.mean(array_5)}")

# Correlation coefficients between array-5 and array_6
print(f"The correlation coefficient of elements in array_5 and array_6 is \n {np.corrcoef(array_5)}")

# Standard deviation of elements in array_5
print(f"The standard deviation of elements in array_5 is {np.std(array_5).round(3)}")

# Variance of elements in array_5
print(f"The variance of elements in array_5 is {np.var(array_5).round(3)}")


The sum of elements in array_5 is: 
 39
The minimum of elements between array_5 and array_6 is: 
 [[1 2 1 7]
 [2 3 6 0]]
The maximum of elements between array_5 and array_6 is: 
 [[ 2  5  5  9]
 [ 4  8  7 10]]
The cummulative sum of elements in array_5 is: 
 [ 1  3  8 17 19 22 29 39]
The mean of elements in array_5 is 4.875
The correlation coefficient of elements in array_5 and array_6 is 
 [[1.        0.9909901]
 [0.9909901 1.       ]]
The standard deviation of elements in array_5 is 3.219
The variance of elements in array_5 is 10.359


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [56]:
# Creating Boolean arrays
array_7 = np.array([True, False, True, True, False])
array_8 = np.array([False, False, False, False, True])

# Applying NOT to the arrays
print(f"array_7 AND array_8 gives: {np.logical_and(array_7, array_8)}")

#Applying OR to the arrays
print(f"array_7 OR array_8 gives: {np.logical_or(array_7, array_8)}")

# Applying NOT to the arrays
print(f"array_7 NOT array_8 gives: {np.logical_not(array_7, array_8)}")

array_7 AND array_8 gives: [False False False False False]
array_7 OR array_8 gives: [ True False  True  True  True]
array_7 NOT array_8 gives: [False  True False False  True]
