# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
# import numpy as np
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [146]:
# Creating 
array_1 = np.array([[[1,2,3,4], [5,6,7,8]],[[9,8,7,6],[5,4,3,2]]])
array_2 = np.ones((3,4,5))
array_3 = np.random.random((3,3,4))

# Slicing arrays so one element or number is returned
print(array_1[1,1])
print(array_2[0,0])
print(array_3[0,1])

# Slicing arrays so one dimension is returned 
print(len(array_1[1,1]))
print(len(array_2[0,0]))
print(len((array_2[2,2])))

# Slicing so a subset of a dimension is returned
print(len(array_1[1:]))
print(len(array_2[:2]))
print(len(array_3[3:2]))

[5 4 3 2]
[1. 1. 1. 1. 1.]
[0.80972534 0.12234732 0.18783618 0.15277483]
4
5
5
1
2
0


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [124]:
#Boolean indexing
print(f"Elements in array_1 greater than 5: \n {array_1 > 5}")
print(f"Elements in array_2 less than 0 : \n {array_2 < 3}")
print(f"Elements in array_3 equal to 0.56712: \n {array_3 == 0.56712}")
print(f"Elements in array_1 greater than or equal to 3: \n {array_1 >=3}")
print(f"Elements in array_1 less than 5 and equal to 3: \n {np.where((array_1 < 5) & (array_1 == 3))}")


Elements in array_1 greater than 5: 
 [[[False False False False]
  [False  True  True  True]]

 [[ True  True  True  True]
  [False False False False]]]
Elements in array_2 less than 0 : 
 [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
Elements in array_3 equal to 0.56712: 
 [[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]
Elements in array_1 greater than or equal to 3: 
 [[[False False  True  True]
  [ True  True  True

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [109]:
# Trying the help function
help(np.transpose)
help(np.delete)

# Yes, the help documentation is pretty detailed. 
# The examples provided is such that I would be to use it just by reading.

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [125]:
# Transposing array_1 using the transpose() function
print(f"The transpose of  \n {array_1} is: \n {np.transpose(array_1)}")

# Transposing array_1 using the T attribute
print(f"The transpose of \n {array_1} is: \n {array_1.T}")


The transpose of  
 [[[1 2 3 4]
  [5 6 7 8]]

 [[9 8 7 6]
  [5 4 3 2]]] is: 
 [[[1 9]
  [5 5]]

 [[2 8]
  [6 4]]

 [[3 7]
  [7 3]]

 [[4 6]
  [8 2]]]
The transpose of 
 [[[1 2 3 4]
  [5 6 7 8]]

 [[9 8 7 6]
  [5 4 3 2]]] is: 
 [[[1 9]
  [5 5]]

 [[2 8]
  [6 4]]

 [[3 7]
  [7 3]]

 [[4 6]
  [8 2]]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [147]:
#Creating new a 3x3 matrix
array_4 = np.array([[1,2,3],[4,5,6], [7,8,9]])

# Creating a matrix and resizing it by adding 2 extra columns 
array_4_resize = np.resize(array_4, (3,5))
print(f" Resizing array_4 from a 3x3 to 3x5 gives: \n {array_4_resize}")

# Creating a matrix by resizing it by adding 1 extra row
array_4_resizeb = np.resize(array_4, (4,3))
print(f" Resizing array_4 from a 3x3 to 4x3 gives: \n {array_4_resizeb}")

# Creating a 8x2 matrix
array_5 = (np.random.random((8,2)).round(1))
array_5_resize = np.resize(array_5, (4,4))
print(f"Resizing array_5 from a 8x2 to 4x4 gives: \n {array_5_resize}")



 Resizing array_4 from a 3x3 to 3x5 gives: 
 [[1 2 3 4 5]
 [6 7 8 9 1]
 [2 3 4 5 6]]
 Resizing array_4 from a 3x3 to 4x3 gives: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
Resizing array_5 from a 8x2 to 4x4 gives: 
 [[0.7 0.4 0.1 0.9]
 [0.6 0.1 0.  0.4]
 [0.6 0.6 0.6 0.2]
 [0.2 0.4 0.8 0.5]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [197]:
# Creating a 3 dimensional array
array_6 = np.array([[[9,8,7,6], [5,4,3,2]],[[1,2,3,4],[5,6,7,8]]])
#print(array_6)

# Appending row to array_6
array_7_appended = np.append(array_6,[9,8,7,6], axis = 0)
print(array_7_appended)
array_7_appended
np.ndim(array_7_appended)



ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)

## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [198]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [199]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
